version: "2.0"

services:
  mongo:
    image: mongo:3.4.2
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=masterpass
    container_name: open-crm
